// AUTO-GENERATED by scripts/sync-catalog.js — do not edit.
export const audio = {
  "Alpha.mp3": require("./assets/audio/Alpha.mp3"),
  "Energizer.mp3": require("./assets/audio/Energizer.mp3"),
  "First Love.mp3": require("./assets/audio/First Love.mp3"),
  "French Roast.mp3": require("./assets/audio/French Roast.mp3"),
  "Lucid Dream.mp3": require("./assets/audio/Lucid Dream.mp3"),
  "Mystery.mp3": require("./assets/audio/Mystery.mp3"),
  "Serene.mp3": require("./assets/audio/Serene.mp3"),
};
