// Catalog access layer. catalog.json + images map are generated by
// scripts/sync-catalog.js. (audio map is imported later, in the player stage.)
import catalog from './catalog.json';
import { images } from './images';

export const CATEGORIES = catalog.categories;
export const DOSES = catalog.doses;

export const imageSource = name => (name && images[name]) || null;

export const dosesByCategory = cat => DOSES.filter(d => d.category === cat);
export const doseById = id => DOSES.find(d => d.id === id);

// One descriptor per category for the springboard (with a representative image).
export const categoryCards = () =>
  CATEGORIES.map(cat => {
    const items = dosesByCategory(cat);
    const withImg = items.find(d => d.image);
    return { name: cat, count: items.length, image: withImg ? withImg.image : null };
  });
